# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tic.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def clicker(self,b):
        if self.counter%2 == 0:
            b.setText("X")
            self.label.setText("X's chance")
        else:
            b.setText("0")
            self.label.setText("0's chance")
   
        b.setEnabled(False)
        self.counter+=1
        self.checkWin()


    def clear1(self):
        button_list=[
         self.pushButton_1,self.pushButton_2,self.pushButton_11,self.pushButton_4,self.pushButton_5,self.pushButton_12,self.pushButton_7,self.pushButton_8,self.pushButton_9]  
        for b in button_list:
                b.setText("")
                b.setEnabled(True)
                b.setStyleSheet('QPushButton{color: #797979;}')
                pass
                

    def checkWin(self):
        if self.pushButton_1.text() != "" and self.pushButton_1.text()==self.pushButton_2.text() and self.pushButton_1.text()== self.pushButton_4.text():
            self.win(self.pushButton_1,self.pushButton_2,self.pushButton_4)
        if self.pushButton_1.text() != "" and self.pushButton_1.text()==self.pushButton_7.text() and self.pushButton_1.text()== self.pushButton_11.text():
            self.win(self.pushButton_1,self.pushButton_7,self.pushButton_11)
        if self.pushButton_2.text() != "" and self.pushButton_2.text()==self.pushButton_5.text() and self.pushButton_2.text()== self.pushButton_12.text():
            self.win(self.pushButton_2,self.pushButton_5,self.pushButton_12)
        if self.pushButton_4.text() != "" and self.pushButton_4.text()==self.pushButton_8.text() and self.pushButton_4.text()== self.pushButton_9.text():
            self.win(self.pushButton_4,self.pushButton_8,self.pushButton_9)
        if self.pushButton_7.text() != "" and self.pushButton_5.text()==self.pushButton_7.text() and self.pushButton_5.text()== self.pushButton_8.text():
            self.win(self.pushButton_7,self.pushButton_5,self.pushButton_8)
        if self.pushButton_11.text() != "" and self.pushButton_11.text()==self.pushButton_12.text() and self.pushButton_11.text()== self.pushButton_9.text():
            self.win(self.pushButton_11,self.pushButton_12,self.pushButton_9)
        if self.pushButton_1.text() != "" and self.pushButton_1.text()==self.pushButton_5.text() and self.pushButton_1.text()== self.pushButton_9.text():
            self.win(self.pushButton_1,self.pushButton_5,self.pushButton_9)
        if self.pushButton_4.text() != "" and self.pushButton_4.text()==self.pushButton_5.text() and self.pushButton_4.text()== self.pushButton_11.text():
            self.win(self.pushButton_4,self.pushButton_5,self.pushButton_11)


        pass

    def win(self,a,b,c):
        a.setStyleSheet('QPushButton{color:red;}')
        b.setStyleSheet('QPushButton{color:red;}')
        c.setStyleSheet('QPushButton{color:red;}')

        self.label.setText(f"{a.text()} Wins!")
        self.disable()


        pass
    def disable(self):
        button_list=[
        self.pushButton_1,
            self.pushButton_2,
            self.pushButton_11,
            self.pushButton_4,self.pushButton_5,self.pushButton_12,self.pushButton_7,self.pushButton_8,self.pushButton_9

            ]  
        for b in button_list:
                b.setEnabled(False)
                pass







    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.counter =0
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 0, 461, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(1, 0, 1, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_7))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_7.setText("")
        self.pushButton_7.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_9))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_9.setText("")
        self.pushButton_9.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 4, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_1.setText("")
        self.pushButton_1.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_5))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_5.setText("")
        self.pushButton_5.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_4))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_4.setText("")
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_12))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_12.setText("")
        self.pushButton_12.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 4, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_8))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_8.setText("")
        self.pushButton_8.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget,clicked=lambda : self.clicker(self.pushButton_11))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_11.setText("")
        self.pushButton_11.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 4, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda : self.clear1())
        self.pushButton_10.setGeometry(QtCore.QRect(50, 440, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 370, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "Play Again"))
        self.label.setText(_translate("MainWindow", "X starts first"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
